# Generated by Django 4.0.3 on 2022-06-28 14:04

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_client_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=backend.models.upload_path),
        ),
    ]
