# Generated by Django 4.0.3 on 2022-06-28 14:40

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_client_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to=backend.models.upload_path),
        ),
    ]
